name: eventful-sql-common
version: "0.1.0"
maintainer: David Reaver
synopsis: Common library for SQL event stores
description: Common library for SQL event stores
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

dependencies:
  - base >= 4.9 && < 5
  - eventful-core

  - aeson
  - bytestring
  - mtl
  - persistent
  - persistent-template
  - split
  - text
  - uuid

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall
