name: eventful-test-helpers
version: "0.1.0"
maintainer: David Reaver
synopsis: Common module used for eventful tests
description: Common module used for eventful tests
maintainer: David Reaver
stability: experimental
license: MIT
license-file: LICENSE.md

dependencies:
  - base
  - eventful-core

  - aeson
  - extra
  - hspec
  - monad-logger

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall
