name: eventful-core
version: "0.1.0"
maintainer: David Reaver
synopsis: Core module for eventful
description: Core module for eventful
maintainer: David Reaver
stability: experimental
license: MIT
license-file: LICENSE.md

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base

  - aeson
  - containers
  - http-api-data
  - path-pieces
  - text
  - uuid

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventful-test-helpers
  style:
    main: HLint.hs
    ghc-options: -Wall -Werror
    source-dirs:
      - tests
    dependencies:
      - hlint
