name: event-sourcing
version: "0.1.0"
maintainer: David Reaver

dependencies:
  - base
  - todomvc-common
  - aeson
  - async
  - bytestring
  - containers
  - directory
  # - esqueleto  # https://github.com/prowdsponsor/esqueleto/issues/137
  - http-api-data
  - monad-logger
  - path-pieces
  - persistent
  - persistent-sqlite
  - persistent-template
  - pipes
  - pipes-concurrency
  - lens
  - mtl
  - random
  - safe
  - split
  - stm
  - text
  - time
  - transformers
  - uuid

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
  style:
    main: HLint.hs
    ghc-options: -Wall -Werror
    source-dirs:
      - tests
    dependencies:
      - hlint
