resolver: nightly-2017-02-18
packages:
  - 'eventful-core'
  - 'eventful-memory'
  - 'eventful-postgresql'
  - 'eventful-sql-common'
  - 'eventful-sqlite'
  - 'eventful-test-helpers'
  - 'examples/cafe'
  - 'examples/counter-cli'
