resolver: nightly-2017-04-30
packages:
  - 'eventful-core'
  - 'eventful-dynamodb'
  - 'eventful-memory'
  - 'eventful-postgresql'
  - 'eventful-sql-common'
  - 'eventful-sqlite'
  - 'eventful-test-helpers'
  - 'examples/bank'
  # - 'examples/cafe'
  - 'examples/counter-cli'
