name: eventful-dynamodb
version: "0.1.3"
maintainer: David Reaver
synopsis: Library for eventful DynamoDB event stores
description: Library for eventful DynamoDB event stores
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing,AWS
license: MIT
license-file: LICENSE.md

github: jdreaver/eventful

dependencies:
  - base >= 4.9 && < 5
  - eventful-core

  - aeson
  - amazonka
  - amazonka-dynamodb
  - bytestring
  - conduit
  - lens
  - safe
  - text
  - unordered-containers
  - vector

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - QuickCheck
      - quickcheck-instances
      - eventful-test-helpers
  style:
    main: HLint.hs
    ghc-options: -Wall
    source-dirs:
      - tests
    dependencies:
      - hlint
