name: examples-bank
version: "0.1.0"
maintainer: David Reaver
synopsis: Example bank application for eventful
description: Example bank application for eventful
maintainer: David Reaver
stability: experimental
license: MIT

dependencies:
  - base
  - eventful-core
  - eventful-sqlite

  - aeson
  - aeson-casing
  - aeson-pretty
  - bytestring
  - containers
  - lens
  - monad-logger
  - mtl
  - optparse-applicative
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe
  - stm
  - text

default-extensions:
  - ExistentialQuantification
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  bank-main:
    main: bank-main.hs
    ghc-options: -Wall
    source-dirs:
      - executables
    dependencies:
      - examples-bank

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
  style:
    main: HLint.hs
    ghc-options: -Wall -Werror
    source-dirs:
      - tests
    dependencies:
      - hlint
