name: examples-cafe
version: "0.1.0"
maintainer: David Reaver
synopsis: Example cafe application for eventful
description: Example cafe application for eventful
maintainer: David Reaver
stability: experimental
license: MIT

dependencies:
  - base
  - eventful-core
  - eventful-sqlite

  - lens
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe

default-extensions:
  - ExistentialQuantification
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  cafe-main:
    main: cafe-main.hs
    ghc-options: -Wall
    source-dirs:
      - app
