name: examples-cafe
version: "0.1.0"
maintainer: David Reaver
synopsis: Example cafe application for eventful
description: Example cafe application for eventful
maintainer: David Reaver
stability: experimental
license: MIT

dependencies:
  - base
  - eventful-core
  - eventful-sqlite

  - aeson
  - aeson-pretty
  - ansi-terminal
  - bytestring
  - containers
  - lens
  - monad-logger
  - mtl
  - optparse-applicative
  - persistent
  - persistent-sqlite
  - persistent-template
  - safe
  - text

default-extensions:
  - ExistentialQuantification
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

executables:
  cafe-main:
    main: cafe-main.hs
    ghc-options: -Wall
    source-dirs:
      - app
    dependencies:
      - examples-cafe

  cafe-chef-todo-main:
    main: cafe-chef-todo-main.hs
    ghc-options: -Wall
    source-dirs:
      - app
    dependencies:
      - examples-cafe
