name: examples
version: "0.1.0"
maintainer: David Reaver
synopsis: Example applications for eventful
description: Example applications for eventful
maintainer: David Reaver
stability: experimental
license: MIT

dependencies:
  - base
  - eventful-core
  - eventful-test-helpers

  - safe

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

executables:
  counter-cli:
    main: counter-cli.hs
    ghc-options: -Wall
    source-dirs:
      - executables
    dependencies:
      - eventful-memory
      - stm
