name: eventful-memory
version: "0.1.0"
maintainer: David Reaver

dependencies:
  - base
  - eventful-core

  - containers
  - safe
  - stm

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventful-test-helpers
  style:
    main: HLint.hs
    ghc-options: -Wall -Werror
    source-dirs:
      - tests
    dependencies:
      - hlint
