name: eventful-memory
version: "0.1.2"
maintainer: David Reaver
synopsis: In-memory implementations for eventful
description: In-memory implementations for eventful
maintainer: David Reaver
stability: experimental
category: Database,Eventsourcing
license: MIT
license-file: LICENSE.md

github: jdreaver/eventful

extra-source-files:
  - CHANGELOG.md
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - eventful-core

  - containers
  - safe
  - stm

library:
  source-dirs:
    - src
  ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    ghc-options: -Wall
    source-dirs:
      - tests
      - src
    dependencies:
      - hspec
      - HUnit
      - eventful-test-helpers
  style:
    main: HLint.hs
    ghc-options: -Wall
    source-dirs:
      - tests
    dependencies:
      - hlint
